# --- \\ tmux

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @continuum-restore 'on'

if-shell 'test "$(uname -s)" = Darwin' \
  "set -g @minimal-tmux-bg '#517696'" \
  "set -g @minimal-tmux-bg '#ed3124'"

set -g status-interval 2

set -g default-terminal "tmux-256color"

# Truecolor (RGB) support
set -as terminal-overrides ',*:Tc'
# Undercurl support
# https://github.com/tmux/tmux/issues/1492#issuecomment-427939241
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# Underscore colors
# https://github.com/tmux/tmux/pull/1771#issuecomment-500906522
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# for nnn file preview
set -g allow-passthrough on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
